- name: Ansible Network Acceessibility Check
  hosts: all
  #ignore_errors: true
  vars_files:
  - port_definition.yaml
  tasks:
  - name: print var
    debug:
      var: port_definitions

  - name: Defining fact initialization
    ansible.builtin.include_tasks: "tasks/init_phases.yaml"
    vars:
      port_definition: "{{ item_port }}"
    with_items: "{{ port_definitions }}"
    loop_control:
      loop_var: item_port
    run_once: true


  - name: Testing Ports
    ansible.builtin.include_tasks: "tasks/start_port_check.yaml"
    vars:
     port_definition: "{{item_port}}"
    with_items: "{{port_definitions}}"
    loop_control:
      loop_var: item_port
    run_once: true


#  - name: Ensure no existing process running
#    shell: |
#      for PIDFILE in $(ls /tmp/ansible_network_health_check*/*PID); do
#         kill -9 $(cat $PIDFILE)
#      done
#      exit 0

#  - name: ensure tmp folder doesnot exist for clean start
#    shell: |
#      rm -rf /tmp/ansible_network_health_check*
